stages:
  - azcli
  - validate
  - plan
  - apply
  - destroy
.base:
  image:
    name: hashicorp/terraform
    entrypoint: [""]
  before_script:
    - cat /etc/apk/repositories
    - apk update
    - apk add ca-certificates curl apt-transport-https lsb-release gnupg
    - curl -sL https://packages.microsoft.com/keys/microsoft.asc |  gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
    - apk update && apk install azure-cli -y
    - terraform init 
validate:
  extends: .base
  stage: validate
  script:
    - terraform validate
plan:
  extends: .base
  stage: plan
  script:
    - terraform plan -out-plan.out
  cache:
    key: plan
    policy: push
    paths:
      - plan.out

apply:
  extends: .base
  stage: apply
  script:
    - terraform apply plan.out
  cache:
    key: plan
    policy: pull
    paths:
      - plan.out
  when: manual

destroy:
  extends: .base
  stage: destroy
  script:
    - terraform destroy -auto-approve
  when: manual